version: '3'
services:
  db:
    image:  cassandra
  web:
    build: .
    command: bash -c "sleep 30 && python manage.py sync_cassandra && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db